config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :fotos

  map.resources :produtos

  map.resources :categorias
  map.resources :paginas

  map.namespace :admin do |admin|
    admin.resources :categorias
    admin.resources :blocos
    admin.resources :paginas
    admin.resources :fotos
    admin.resources :produtos
  end

  map.with_options :controller => "pagina" do |p|
    p.people "/people",     :action => "index"
    p.person "/people/:id", :action => "show"
  end


  map.root :controller => :paginas, :action => :index
  map.admin "/admin", :controller => "admin/dashboard", :action => :index

  map.connect ':controller/:action/:id'
  #map.connect ':permalink'
  map.connect ':controller/:action/:id.:format'
end

app/models/produto.rb
class Produto < ActiveRecord::Base

  has_and_belongs_to_many :categorias

  has_permalink :titulo, :update => true

  def to_param
    permalink
  end
end

app/controllers/admin/produtos_controller.rb
class Admin::ProdutosController < ApplicationController

  layout "admin"

  def index
    @produtos = Produto.all
  end

  def show
    @produto = Produto.find_by_permalink(params[:id])
  end

  def new
    @produto = Produto.new
  end

  def create
    @produto = Produto.new(params[:produto])
    if @produto.save
      flash[:notice] = "Successfully created produto."
      redirect_to admin_produtos_path
    else
      render :action => 'new'
    end
  end

  def edit
    @produto = Produto.find_by_permalink(params[:id])
  end

  def update
    @produto = Produto.find_by_permalink(params[:id])
    if @produto.update_attributes(params[:produto])
      redirect_to admin_produtos_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @produto = Produto.find_by_permalink(params[:id])
    @produto.destroy
      redirect_to admin_produtos_path
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  def show
    @produto = Produto.find_by_permalink(params[:id])
  end

end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/admin/produtos/_form.html.erb
<% form_for [:admin,@produto] do |f| %>
  <%= f.error_messages %>
  <br style="clear:both" />
<p>
<!-- %= recaptcha_tags :ajax => true % -->
</p>
  <p>
    <%= f.label :meta_title %><br />
    <%= f.text_field :meta_title %>
  </p>
  <p>
    <%= f.label :meta_description %><br />
    <%= f.text_area :meta_description, :size => "50x5" %>
  </p>
  <p>
    <%= f.label :meta_keyword %><br />
    <%= f.text_area :meta_keyword, :size => "50x5" %>
  </p>
  <p>
    <%= f.label :titulo %> <span class="required">*</span><br />
    <%= f.text_field :titulo %>
  </p>
  <p>
    <%= f.label :descricao %> <span class="required">*</span><br />
    <%= f.text_area :descricao, :size => "50x10" %>
  </p>
  <p>
    <%= f.label :preco %> <span class="required">*</span><br />
    <%= f.text_field :preco, :value => number_with_precision(@produto.preco, :precision => 2) %>
  </p>
  <p>
    <%= f.label :preco_promocional %><br />
    <%= f.text_field :preco_promocional, :value => number_with_precision(@produto.preco_promocional, :precision => 2)  %>
  </p>
  <p>
    <%= f.check_box :status %>
    <%= f.label :status %> <br />
  </p>
    <p>
    <%= f.label :categoria_id, "Categoria do Produto" %><br />
    <ul id="tree" class="filetree">
    <% for categoria in Categoria.roots %>
      <li>
        <%= check_box_tag "produto[categoria_ids][]", categoria.id, @produto.categorias.include?(categoria) %>
        <%= categoria.nome %>
        <% if categoria.children? %>
          <ul>
            <% for categoria in categoria.children %>
              <li>
                <%= check_box_tag "produto[categoria_ids][]", categoria.id, @produto.categorias.include?(categoria) %>
                <%= categoria.nome %>
                <% if categoria.children? %>
                  <ul>
                    <% for categoria in categoria.children %>
                      <li>
                        <%= check_box_tag "produto[categoria_ids][]", categoria.id, @produto.categorias.include?(categoria) %>
                        <%= categoria.nome %>
                        <% if categoria.children? %>
                          <ul>
                            <% for categoria in categoria.children %>
                              <li>
                                <%= check_box_tag "produto[categoria_ids][]", categoria.id, @produto.categorias.include?(categoria) %>
                                <%= categoria.nome %>
                              </li>
                            <% end %>
                            </ul>
                        <% end %>
                      </li>
                    <% end %>
                    </ul>
                <% end %>
              </li>
            <% end %>
            </ul>
        <% end %>
      </li>
    <% end %>
    </ul>
  </p>
  <p><%= f.submit "Salvar" %></p>
<% end %>

app/views/admin/produtos/edit.html.erb
<% title "Admin / Produto" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Voltar", admin_produtos_path %>
</p>

app/views/admin/produtos/index.html.erb
<% title "Produtos" %>

<table>
  <tr>
    <th>Titulo</th>
    <th>Status</th>
  </tr>
  <% for produto in @produtos %>
    <tr>
      <td><%=h produto.titulo %></td>
      <td><%=h produto.status %></td>
      <td><%= link_to "Show", [:admin,produto] %></td>
      <td><%= link_to "Edit", edit_admin_produto_path(produto) %></td>
      <td><%= link_to "Destroy", [:admin,produto], :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Produto", new_admin_produto_path %></p>

app/views/admin/produtos/new.html.erb
<% title "Admin / Produto" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Voltar", admin_produtos_path %>
</p>

app/views/admin/produtos/show.html.erb
<% title "Admin / Produto" %>

<h1>
  <%=h @produto.titulo %>
</h1>
<p>
  <strong>Meta Title:</strong>
  <%=h @produto.meta_title %>
</p>
<p>
  <strong>Meta Description:</strong>
  <%=h @produto.meta_description %>
</p>
<p>
  <strong>Meta Keyword:</strong>
  <%=h @produto.meta_keyword %>
</p>


  <%= simple_format(@produto.descricao) %>



<p>
  <%= link_to "Voltar", admin_produtos_path %>
</p>